import Foundation

enum AppCopy {
    static let translations: [String: (ru: String, en: String)] = [
        "menu.session.title": ("Сеанс", "Session"),
        "menu.app.about": ("О Selective Remote", "About Selective Remote"),
        "menu.cloud.settings": ("Открыть настройки Cloud…", "Open Cloud Settings…"),
        "menu.cloud.browser": ("Открыть Cloud в браузере…", "Open Cloud in Browser…"),
        "menu.session.quick_connect": ("Быстрое подключение…", "Quick Connect…"),
        "menu.help.yoomoney": ("ЮMoney…", "YooMoney…"),
        "menu.help.sberbank": ("СберБанк…", "SberBank…"),
        "menu.sftp.resume": ("Продолжить SFTP-передачи", "Resume SFTP Transfers"),
        "menu.sftp.pause": ("Приостановить SFTP-передачи", "Pause SFTP Transfers"),
        "menu.sftp.cancel": ("Отменить SFTP-передачи", "Cancel SFTP Transfers"),
        "menu.rdp.language": ("Сменить язык", "Switch Language"),
        "menu.rdp.full_screen": ("Полный экран / окно", "Full Screen / Window"),
        "menu.rdp.disconnect": ("Отключить", "Disconnect"),
        "settings.tab.appearance": ("Оформление", "Appearance"),
        "settings.tab.updates": ("Обновления", "Updates"),
        "settings.tab.security": ("Безопасность", "Security"),
        "settings.tab.cloud": ("Cloud", "Cloud"),
        "settings.tab.backup": ("Резервная копия", "Backup"),
        "settings.reset_appearance": ("Сбросить оформление", "Reset Appearance"),
        "appearance.section.theme": ("Внешний вид", "Appearance"),
        "appearance.theme": ("Тема приложения", "App theme"),
        "appearance.text_size": ("Размер текста", "Text size"),
        "appearance.density": ("Плотность интерфейса", "UI density"),
        "appearance.help.text_size": (
            "Размер текста меняется нативно, без масштабирования всего окна. Retina/DPI macOS остаётся системным.",
            "Text size changes natively without scaling the entire window. macOS Retina/DPI remains system-managed."
        ),
        "appearance.section.window": ("Окно приложения", "Application Window"),
        "appearance.transparent_window": ("Прозрачное окно", "Transparent Window"),
        "appearance.opacity": ("Непрозрачность", "Opacity"),
        "appearance.help.opacity": (
            "Системное размытие остаётся активным. Непрозрачность меняет только фон — текст и кнопки сохраняют контраст.",
            "System blur remains active. Opacity changes only the background; text and buttons retain contrast."
        ),
        "appearance.section.language": ("Язык приложения", "Application Language"),
        "appearance.language": ("Язык", "Language"),
        "appearance.help.language": (
            "Интерфейс переключается сразу. Системный режим использует язык macOS.",
            "The interface switches immediately. System mode follows the macOS language."
        ),
        "appearance.section.terminal": ("Терминал", "Terminal"),
        "appearance.section.individual": ("Индивидуальное оформление", "Individual Appearance"),
        "appearance.help.individual": (
            "Тема, шрифт, курсор, подсветка синтаксиса и своя палитра сохраняются только для этой вкладки терминала.",
            "Theme, font, cursor, syntax highlighting, and custom palette are saved only for this terminal tab."
        ),
        "appearance.copy_general": ("Скопировать общее оформление", "Copy General Appearance"),
        "appearance.background": ("Фон и прозрачность", "Background and Transparency"),
        "appearance.transparent_terminal": ("Прозрачный фон терминала", "Transparent Terminal Background"),
        "appearance.background_opacity": ("Непрозрачность фона", "Background Opacity"),
        "appearance.help.terminal_background": (
            "Единая настройка для всех открытых и новых терминалов. Она действует отдельно от прозрачности окна приложения; текст, курсор и панели управления остаются контрастными.",
            "One setting for all open and new terminals. It is separate from app-window transparency; text, cursor, and controls retain contrast."
        ),
        "appearance.font_cursor": ("Шрифт и курсор", "Font and Cursor"),
        "appearance.font": ("Шрифт", "Font"),
        "appearance.size": ("Размер", "Size"),
        "appearance.line_height": ("Межстрочный интервал", "Line Spacing"),
        "appearance.cursor": ("Курсор", "Cursor"),
        "appearance.blink_cursor": ("Мигающий курсор", "Blinking Cursor"),
        "appearance.padding": ("Внутренний отступ", "Padding"),
        "appearance.syntax": ("Подсветка синтаксиса", "Syntax Highlighting"),
        "appearance.highlight_commands": ("Подсветка команд", "Highlight Commands"),
        "appearance.scope": ("Область", "Scope"),
        "appearance.theme_colors": ("Цвета из темы", "Use Theme Colors"),
        "appearance.bold_commands": ("Выделять команды жирным", "Bold Commands"),
        "appearance.previous_commands": ("Предыдущие команды", "Previous Commands"),
        "appearance.reset_syntax": ("Сбросить цвета к текущей теме", "Reset Colors to Current Theme"),
        "appearance.syntax_visible_help": (
            "Подсвечиваются shell-команды в видимой области. Вывод сервера и его ANSI-цвета не изменяются.",
            "Shell commands in the visible area are highlighted. Server output and its ANSI colors are unchanged."
        ),
        "appearance.syntax_current_help": (
            "Подсвечивается только текущая shell-команда. Вывод сервера и его ANSI-цвета не изменяются.",
            "Only the current shell command is highlighted. Server output and its ANSI colors are unchanged."
        ),
        "appearance.custom_theme": ("Своя тема", "Custom Theme"),
        "appearance.color.background": ("Фон", "Background"),
        "appearance.color.text": ("Текст", "Text"),
        "appearance.color.command": ("Команда", "Command"),
        "appearance.color.option": ("Параметр", "Option"),
        "appearance.color.string": ("Строка", "String"),
        "appearance.color.path": ("Путь", "Path"),
        "appearance.color.variable": ("Переменная", "Variable"),
        "appearance.color.number": ("Число", "Number"),
        "appearance.color.operation": ("Оператор", "Operator"),
        "appearance.color.comment": ("Комментарий", "Comment"),
        "appearance.cursor.block": ("Блок", "Block"),
        "appearance.cursor.bar": ("Вертикальный", "Bar"),
        "appearance.cursor.underline": ("Подчёркивание", "Underline"),
        "appearance.scope.current": ("Текущая строка", "Current Line"),
        "appearance.scope.visible": ("Все команды на экране", "All Visible Commands"),
        "backup.restore": ("Восстановить", "Restore"),
        "menu.terminal.new_tab": ("Новая вкладка терминала", "New Terminal Tab"),
        "menu.whats_new": ("Что нового…", "What's New…"),
        "menu.help.title": ("Справка Selective Remote", "Selective Remote Help"),
        "menu.session.unlock": ("Разблокировать Selective Remote", "Unlock Selective Remote"),
        "menu.session.disable_lock": ("Отключить App Lock…", "Turn Off App Lock…"),
        "menu.session.lock": ("Заблокировать Selective Remote", "Lock Selective Remote"),
        "menu.session.no_rdp": ("Активных RDP-сессий нет", "No active RDP sessions"),
        "menu.session.rdp_panel": ("Панель управления RDP…", "RDP Control Panel…"),
        "menu.session.disconnect_all": ("Отключить все", "Disconnect All"),
        "menu.session.stop_ssh_tunnels": ("Остановить все SSH-туннели", "Stop All SSH Tunnels"),
        "menu.session.disconnect_ssh": ("Отключить все SSH-сессии", "Disconnect All SSH Sessions"),
        "menu.session.stop_local_terminals": ("Завершить все локальные терминалы", "Close All Local Terminals"),
        "menu.session.import_profiles": ("Импортировать профили…", "Import Profiles…"),
        "menu.session.export_profiles": ("Экспортировать все профили…", "Export All Profiles…"),
        "menu.session.check_updates": ("Проверить обновления…", "Check for Updates…"),
        "menu.session.quit": ("Завершить Selective Remote", "Quit Selective Remote"),
        "menu.session.show_main": ("Показать Selective Remote", "Show Selective Remote"),
        "menu.session.ssh_tunnels_count": ("SSH-туннелей", "SSH tunnels"),
        "menu.session.ssh_sessions_count": ("SSH-сессий", "SSH sessions"),
        "menu.session.local_terminals_count": ("Локальных терминалов", "Local terminals"),
        "menu.favorites": ("Избранное", "Favorites"),
        "menu.connected": ("подключено", "connected"),
        "menu.connect": ("Подключить", "Connect"),
        "menu.no_rdp_running": ("RDP-сессии не запущены", "No RDP sessions running"),
        "menu.active_sessions": ("Активных сессий", "Active sessions"),
        "menu.open_control_panel": ("Открыть панель управления…", "Open Control Panel…"),
        "menu.shortcut.full_screen": ("Правый Shift + Enter — полный экран / окно", "Right Shift + Enter — full screen / window"),
        "menu.shortcut.disconnect": ("Правый Shift + D — отключить RDP", "Right Shift + D — disconnect RDP"),
        "hosts.auth.automatic.help": (
            "OpenSSH попробует выбранный ключ, ssh-agent и затем пароль. Удобно для совместимости.",
            "OpenSSH tries the selected key, ssh-agent, then a password for compatibility."
        ),
        "hosts.auth.password.help": ("Используется только SSH-пароль. Public key authentication отключена.", "Only the SSH password is used. Public-key authentication is disabled."),
        "hosts.auth.key.help": ("Используется только выбранный SSH-ключ. Пароль не будет fallback-вариантом.", "Only the selected SSH key is used. Password fallback is disabled."),
        "hosts.auth.touch_id.help": ("Touch ID Key — отдельный тип входа: используется только ECDSA-ключ и перед каждым использованием требуется Touch ID. На сервер устанавливается обычный публичный ECDSA-ключ.", "Touch ID Key is a separate sign-in method: it uses an ECDSA key and requires Touch ID for every use. Install its standard ECDSA public key on the server."),
        "hosts.auth.agent.help": ("Используются только системный ssh-agent и ~/.ssh/config.", "Only the system ssh-agent and ~/.ssh/config are used."),
        "hosts.auth.agent.detail": ("Selective Remote использует системный ssh-agent и ~/.ssh/config. Пароль и выбранный SSH ID профиля не передаются OpenSSH.", "Selective Remote uses the system ssh-agent and ~/.ssh/config. The profile's password and selected SSH ID are not passed to OpenSSH."),
        "hosts.proxy.http.help": ("HTTP CONNECT: Basic-аутентификация выполняется защищённым helper-процессом; пароль не попадает в аргументы OpenSSH.", "HTTP CONNECT: Basic authentication runs in a protected helper; the password is not passed as an OpenSSH argument."),
        "hosts.proxy.socks.help": ("SOCKS5: поддерживаются анонимный режим и username/password; пароль хранится в Keychain и передаётся helper-процессу через временный файл 0600.", "SOCKS5 supports anonymous and username/password modes. The password stays in Keychain and reaches the helper through a temporary mode-0600 file."),
        "terminal.local.restart": ("Перезапустить shell", "Restart Shell"),
        "terminal.local.start": ("Запустить shell", "Start Shell"),
        "terminal.local.accessibility": ("Локальный терминал", "Local Terminal"),
        "terminal.local.invalid_connection": ("Локальная вкладка содержит неверный тип подключения", "The local tab has an invalid connection type"),
        "terminal.local.already_running": ("Этот локальный терминал уже запущен", "This local terminal is already running"),
        "terminal.local.finished": ("Локальный терминал завершён", "Local Terminal finished"),
        "terminal.local.finished_with_code": ("Локальный терминал завершился с кодом", "Local Terminal exited with code"),
        "terminal.local.started": ("Локальный терминал запущен", "Local Terminal started"),
        "terminal.local.not_started": ("Локальный терминал не запущен", "Local Terminal did not start"),
        "terminal.local.description": ("Локальный терминал запускает login shell текущего пользователя внутри псевдотерминала. История хранится только на этом Mac; строки с признаками секретов не сохраняются.", "The local terminal runs your login shell in a pseudoterminal. History stays on this Mac, and commands that look like secrets are not saved."),
        "terminal.local.pin": ("Закрепить", "Pin"),
        "terminal.local.unpin": ("Открепить", "Unpin"),
        "terminal.remote.temporary_background_help": ("Для временного фонового подключения используйте SSH-ключ, системный ssh-agent или ~/.ssh/config. Для пароля сохраните подключение как SSH-профиль.", "For a temporary background connection, use an SSH key, the system ssh-agent, or ~/.ssh/config. To use a password, save the connection as an SSH profile."),
        "terminal.remote.temporary_interactive_help": ("Для временного подключения используется системный ssh-agent и ~/.ssh/config; при необходимости OpenSSH запросит пароль отдельно.", "Temporary connections use the system ssh-agent and ~/.ssh/config; OpenSSH may ask for a password separately."),
        "connection.updated.just_now": ("Обновлено только что", "Updated just now"),
        "updates.status.checking": ("Проверка…", "Checking…"),
        "updates.status.current": ("Установлена актуальная версия", "Up to Date"),
        "updates.last_check.never": ("Ещё не выполнялась", "Never"),
        "help.support.title": ("Поддержать проект", "Support the Project"),
        "help.support.choose": ("Выбрать способ поддержки", "Choose a Way to Support"),
        "ssh.error.invalid_host": ("Укажите корректный hostname, IP-адрес или Host из ~/.ssh/config", "Enter a valid hostname, IP address, or Host from ~/.ssh/config"),
        "ssh.error.invalid_username": ("Имя пользователя SSH содержит недопустимые пробелы или управляющие символы", "The SSH username contains invalid whitespace or control characters"),
        "ssh.error.invalid_port": ("Порт SSH должен быть в диапазоне 1…65535", "The SSH port must be between 1 and 65535"),
        "ssh.error.invalid_directory": ("Начальная папка SFTP не должна содержать переносы строк", "The initial SFTP folder cannot contain line breaks"),
        "ssh.error.missing_forward_destination": ("Для локального или удалённого туннеля укажите конечный host и порт", "Enter a destination host and port for a local or remote tunnel"),
        "ssh.error.incompatible_touch_id": ("Touch ID Key поддерживает только обычные ECDSA-ключи. Выберите ECDSA ключ или создайте новый Touch ID Key.", "Touch ID Key supports standard ECDSA keys only. Select an ECDSA key or create a new Touch ID Key."),
        "ssh.error.select_identity": ("Выберите SSH-ключ для выбранного способа входа", "Select an SSH key for this authentication method"),
        "ssh.error.agent_socket": ("встроенный ssh-agent не создал защищённый сокет", "the bundled ssh-agent did not create a secure socket"),
        "ssh.error.not_private_key": ("Выберите приватный SSH-ключ, а не файл .pub", "Select a private SSH key, not a .pub file"),
        "ssh.error.askpass_missing": ("В пакете отсутствует помощник Keychain. Пересоберите приложение scripts/build_app.sh", "The Keychain helper is missing from the app bundle. Rebuild the app with scripts/build_app.sh"),
        "ssh.error.public_key_missing": ("Рядом с приватным ключом не найден файл публичного ключа .pub", "No .pub public-key file was found beside the private key"),
        "ssh.error.invalid_key_path": ("Укажите корректный путь для нового приватного SSH-ключа", "Choose a valid path for the new private SSH key"),
        "ssh.key.ed25519_title": ("Ed25519 — рекомендуется", "Ed25519 — Recommended"),
        "ssh.key.rsa_title": ("RSA 4096 — для старых серверов", "RSA 4096 — For Older Servers"),
        "ssh.touch_id.password": ("Подтвердите Touch ID для использования SSH-пароля", "Confirm Touch ID to use the SSH password"),
        "ssh.touch_id.jump_password": ("Подтвердите Touch ID для использования пароля Jump Host", "Confirm Touch ID to use the Jump Host password"),
        "ssh.error.secret_channel": ("не удалось подготовить защищённый канал секрета", "could not prepare a secure channel for the secret"),
        "ssh.fingerprint.unknown": ("не определён", "unknown"),
        "ssh.error.unknown": ("неизвестная ошибка", "unknown error")
    ]
}
