import Foundation

enum AppCopy {
    static let translations: [String: (ru: String, en: String)] = [
        "menu.session.title": ("Сессия", "Session"),
        "menu.terminal.new_tab": ("Новая вкладка терминала", "New Terminal Tab"),
        "menu.whats_new": ("Что нового…", "What's New…"),
        "menu.help.title": ("Справка Selective Remote", "Selective Remote Help"),
        "menu.session.unlock": ("Разблокировать Selective Remote", "Unlock Selective Remote"),
        "menu.session.disable_lock": ("Отключить App Lock…", "Turn Off App Lock…"),
        "menu.session.lock": ("Заблокировать Selective Remote", "Lock Selective Remote"),
        "menu.session.no_rdp": ("Активных RDP-сессий нет", "No active RDP sessions"),
        "menu.session.rdp_panel": ("Панель управления RDP…", "RDP Control Panel…"),
        "menu.session.disconnect_all": ("Отключить все", "Disconnect All"),
        "menu.session.stop_ssh_tunnels": ("Остановить все SSH-туннели", "Stop All SSH Tunnels"),
        "menu.session.disconnect_ssh": ("Отключить все SSH-сессии", "Disconnect All SSH Sessions"),
        "menu.session.stop_local_terminals": ("Завершить все локальные терминалы", "Close All Local Terminals"),
        "menu.session.import_profiles": ("Импортировать профили…", "Import Profiles…"),
        "menu.session.export_profiles": ("Экспортировать все профили…", "Export All Profiles…"),
        "menu.session.check_updates": ("Проверить обновления…", "Check for Updates…"),
        "menu.session.quit": ("Завершить Selective Remote", "Quit Selective Remote"),
        "menu.session.show_main": ("Показать Selective Remote", "Show Selective Remote"),
        "menu.session.ssh_tunnels_count": ("SSH-туннелей", "SSH tunnels"),
        "menu.session.ssh_sessions_count": ("SSH-сессий", "SSH sessions"),
        "menu.session.local_terminals_count": ("Локальных терминалов", "Local terminals"),
        "menu.favorites": ("Избранное", "Favorites"),
        "menu.connected": ("подключено", "connected"),
        "menu.connect": ("Подключить", "Connect"),
        "menu.no_rdp_running": ("RDP-сессии не запущены", "No RDP sessions running"),
        "menu.active_sessions": ("Активных сессий", "Active sessions"),
        "menu.open_control_panel": ("Открыть панель управления…", "Open Control Panel…"),
        "menu.shortcut.full_screen": ("Правый Shift + Enter — полный экран / окно", "Right Shift + Enter — full screen / window"),
        "menu.shortcut.disconnect": ("Правый Shift + D — отключить RDP", "Right Shift + D — disconnect RDP"),
        "hosts.auth.automatic.help": (
            "OpenSSH попробует выбранный ключ, ssh-agent и затем пароль. Удобно для совместимости.",
            "OpenSSH tries the selected key, ssh-agent, then a password for compatibility."
        ),
        "hosts.auth.password.help": ("Используется только SSH-пароль. Public key authentication отключена.", "Only the SSH password is used. Public-key authentication is disabled."),
        "hosts.auth.key.help": ("Используется только выбранный SSH-ключ. Пароль не будет fallback-вариантом.", "Only the selected SSH key is used. Password fallback is disabled."),
        "hosts.auth.touch_id.help": ("Touch ID Key — отдельный тип входа: используется только ECDSA-ключ и перед каждым использованием требуется Touch ID. На сервер устанавливается обычный публичный ECDSA-ключ.", "Touch ID Key is a separate sign-in method: it uses an ECDSA key and requires Touch ID for every use. Install its standard ECDSA public key on the server."),
        "hosts.auth.agent.help": ("Используются только системный ssh-agent и ~/.ssh/config.", "Only the system ssh-agent and ~/.ssh/config are used."),
        "hosts.auth.agent.detail": ("Selective Remote использует системный ssh-agent и ~/.ssh/config. Пароль и выбранный SSH ID профиля не передаются OpenSSH.", "Selective Remote uses the system ssh-agent and ~/.ssh/config. The profile's password and selected SSH ID are not passed to OpenSSH."),
        "hosts.proxy.http.help": ("HTTP CONNECT: Basic-аутентификация выполняется защищённым helper-процессом; пароль не попадает в аргументы OpenSSH.", "HTTP CONNECT: Basic authentication runs in a protected helper; the password is not passed as an OpenSSH argument."),
        "hosts.proxy.socks.help": ("SOCKS5: поддерживаются анонимный режим и username/password; пароль хранится в Keychain и передаётся helper-процессу через временный файл 0600.", "SOCKS5 supports anonymous and username/password modes. The password stays in Keychain and reaches the helper through a temporary mode-0600 file."),
        "terminal.local.restart": ("Перезапустить shell", "Restart Shell"),
        "terminal.local.start": ("Запустить shell", "Start Shell"),
        "terminal.local.accessibility": ("Локальный терминал", "Local Terminal"),
        "terminal.local.description": ("Локальный терминал запускает login shell текущего пользователя внутри псевдотерминала. История хранится только на этом Mac; строки с признаками секретов не сохраняются.", "The local terminal runs your login shell in a pseudoterminal. History stays on this Mac, and commands that look like secrets are not saved."),
        "terminal.local.pin": ("Закрепить", "Pin"),
        "terminal.local.unpin": ("Открепить", "Unpin"),
        "terminal.remote.temporary_background_help": ("Для временного фонового подключения используйте SSH-ключ, системный ssh-agent или ~/.ssh/config. Для пароля сохраните подключение как SSH-профиль.", "For a temporary background connection, use an SSH key, the system ssh-agent, or ~/.ssh/config. To use a password, save the connection as an SSH profile."),
        "terminal.remote.temporary_interactive_help": ("Для временного подключения используется системный ssh-agent и ~/.ssh/config; при необходимости OpenSSH запросит пароль отдельно.", "Temporary connections use the system ssh-agent and ~/.ssh/config; OpenSSH may ask for a password separately."),
        "connection.updated.just_now": ("Обновлено только что", "Updated just now"),
        "updates.status.checking": ("Проверка…", "Checking…"),
        "updates.status.current": ("Установлена актуальная версия", "Up to Date"),
        "updates.last_check.never": ("Ещё не выполнялась", "Never"),
        "help.support.title": ("Поддержать проект", "Support the Project"),
        "help.support.choose": ("Выбрать способ поддержки", "Choose a Way to Support"),
        "ssh.error.invalid_host": ("Укажите корректный hostname, IP-адрес или Host из ~/.ssh/config", "Enter a valid hostname, IP address, or Host from ~/.ssh/config"),
        "ssh.error.invalid_username": ("Имя пользователя SSH содержит недопустимые пробелы или управляющие символы", "The SSH username contains invalid whitespace or control characters"),
        "ssh.error.invalid_port": ("Порт SSH должен быть в диапазоне 1…65535", "The SSH port must be between 1 and 65535"),
        "ssh.error.invalid_directory": ("Начальная папка SFTP не должна содержать переносы строк", "The initial SFTP folder cannot contain line breaks"),
        "ssh.error.missing_forward_destination": ("Для локального или удалённого туннеля укажите конечный host и порт", "Enter a destination host and port for a local or remote tunnel"),
        "ssh.error.incompatible_touch_id": ("Touch ID Key поддерживает только обычные ECDSA-ключи. Выберите ECDSA ключ или создайте новый Touch ID Key.", "Touch ID Key supports standard ECDSA keys only. Select an ECDSA key or create a new Touch ID Key."),
        "ssh.error.select_identity": ("Выберите SSH-ключ для выбранного способа входа", "Select an SSH key for this authentication method"),
        "ssh.error.agent_socket": ("встроенный ssh-agent не создал защищённый сокет", "the bundled ssh-agent did not create a secure socket"),
        "ssh.error.not_private_key": ("Выберите приватный SSH-ключ, а не файл .pub", "Select a private SSH key, not a .pub file"),
        "ssh.error.askpass_missing": ("В пакете отсутствует помощник Keychain. Пересоберите приложение scripts/build_app.sh", "The Keychain helper is missing from the app bundle. Rebuild the app with scripts/build_app.sh"),
        "ssh.error.public_key_missing": ("Рядом с приватным ключом не найден файл публичного ключа .pub", "No .pub public-key file was found beside the private key"),
        "ssh.error.invalid_key_path": ("Укажите корректный путь для нового приватного SSH-ключа", "Choose a valid path for the new private SSH key"),
        "ssh.key.ed25519_title": ("Ed25519 — рекомендуется", "Ed25519 — Recommended"),
        "ssh.key.rsa_title": ("RSA 4096 — для старых серверов", "RSA 4096 — For Older Servers"),
        "ssh.touch_id.password": ("Подтвердите Touch ID для использования SSH-пароля", "Confirm Touch ID to use the SSH password"),
        "ssh.touch_id.jump_password": ("Подтвердите Touch ID для использования пароля Jump Host", "Confirm Touch ID to use the Jump Host password"),
        "ssh.error.secret_channel": ("не удалось подготовить защищённый канал секрета", "could not prepare a secure channel for the secret"),
        "ssh.fingerprint.unknown": ("не определён", "unknown"),
        "ssh.error.unknown": ("неизвестная ошибка", "unknown error")
    ]
}
