const operationStatuses = Object.freeze({
  registration_disabled: 403,
  invalid_credentials: 401,
  email_not_verified: 403,
  smtp_not_configured: 503,
  rate_limited: 429,
  invalid_verification_token: 400,
  invalid_password_reset_token: 400,
  invalid_email: 400,
  invalid_password: 400,
  invalid_device: 400,
  invalid_device_public_key: 400,
  device_public_key_mismatch: 409,
  device_not_found: 404,
  device_approval_required: 403,
  invalid_content_type: 415,
  invalid_json: 400,
  request_too_large: 413,
  invalid_vault_envelope: 400,
  invalid_wrapped_key: 400,
  invalid_base_revision: 400,
  invalid_envelope_version: 400,
  invalid_key_generation: 409,
  invalid_team_vault_wrapper: 400,
  invalid_team_vault_wrapper_context: 400,
  invalid_team_vault_wrappers: 400,
  incomplete_team_vault_wrappers: 409,
  unexpected_team_vault_wrappers: 400,
  team_vault_key_unavailable: 403,
  team_vault_conflict: 409,
  vault_too_large: 413,
  vault_missing: 404,
  invalid_team: 400,
  invalid_team_role: 400,
  invalid_shared_vault: 400,
  invalid_idempotency_key: 400,
  invalid_team_invitation: 400,
  team_not_found: 404,
  team_access_denied: 403,
  team_member_exists: 409,
  team_last_owner: 409,
  shared_vault_exists: 409,
  shared_vault_wrapper_exists: 409,
});

export function publicOperationError(error) {
  const code = error?.message;
  const status = operationStatuses[code];
  return status ? { status, code } : null;
}
