name: Предложить функцию
description: Идея для развития Selective Remote
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Какую проблему решает функция?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Предлагаемое поведение
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Альтернативы
